-- CREATE TABLE users(
-- 	id SERIAL PRIMARY KEY,
-- 	name TEXT NOT NULL
-- );

-- CREATE TABLE orders(
-- 	id SERIAL PRIMARY KEY,
-- 	user_id INT NOT NULL,
-- 	total INT NOT NULL,
-- 	created_at DATE NOT NULL DEFAULT CURRENT_DATE
-- )

-- INSERT INTO users (name)
-- VALUES
-- ('Aruzhan'),
-- ('Daniyar'),
-- ('Sasha'),
-- ('Anna');

-- INSERT INTO orders (user_id, total, created_at) 
-- VALUES 
-- (1, 12000, '2026-01-10'),
-- (1, 5000, '2026-01-12'),
-- (2, 7000, '2026-01-11'),
-- (3, 15000, '2026-01-15')

-- FROM users u
-- JOIN orders o 
-- ON u.id = o.user_id

-- INNER JOIN
-- SELECT u.name, o.total, o.created_at
-- FROM users u
-- INNER JOIN orders o ON u.id = o.user_id \

-- LEFT JOIN
-- SELECT u.name, o.total
-- FROM users u
-- LEFT JOIN orders o ON u.id = o.user_id

-- SELECT u.name
-- FROM users u
-- LEFT JOIN orders o ON u.id = o.user_id
-- WHERE o.id IS NULL

-- RIGHT JOIN
-- SELECT u.name,o.total
-- FROM orders o
-- RIGHT JOIN users u ON o.user_id = u.id

-- FULL JOIN
-- SELECT u.name,o.total
-- FROM users u
-- FULL JOIN orders o ON u.id = o.user_id

-- ПРАКТИКА
-- CREATE TABLE users2(
-- 	id SERIAL PRIMARY KEY,
-- 	name TEXT NOT NULL
-- );

-- CREATE TABLE categories(
-- 	id SERIAL PRIMARY KEY,
-- 	title TEXT NOT NULL
-- );
-- CREATE TABLE orders2(
-- 	id SERIAL PRIMARY KEY,
-- 	user_id INT NOT NULL REFERENCES users2(id),
-- 	created_at DATE NOT NULL DEFAULT CURRENT_DATE
-- );
-- CREATE TABLE products(
-- 	id SERIAL PRIMARY KEY,
-- 	title TEXT NOT NULL,
-- 	price INT NOT NULL,
-- 	category_id INT NOT NULL REFERENCES categories(id)
-- );
-- CREATE TABLE order_items(
-- 	id SERIAL PRIMARY KEY,
-- 	order_id INT NOT NULL REFERENCES orders2(id),
-- 	product_id INT NOT NULL REFERENCES products(id),
-- 	qty INT NOT NULL CHECK (qty > 0)
-- )

-- INSERT INTO users2 (name)
-- VALUES
-- ('Platon'),
-- ('Elmira'),
-- ('Sayat');
-- INSERT INTO categories (title) 
-- VALUES
-- ('Electronics'),
-- ('Food'),
-- ('Books');
-- INSERT INTO products (title,price,category_id)
-- VALUES 
-- ('Headphones', 15000, 1),
-- ('Keyboard', 22000, 1),
-- ('Chocolate', 1000, 2),
-- ('Base SQL', 7000, 3);
-- INSERT INTO orders2 (user_id, created_at)
-- VALUES
-- (1, '2026-01-10'),
-- (1, '2026-01-12'),
-- (2, '2026-01-11');
-- INSERT INTO order_items(order_id, product_id, qty)
-- VALUES
-- (1,1,1),
-- (1,3,3),
-- (2,4,1),
-- (3,2,1);

-- 1)Список товаров с категорией
-- SELECT p.title, p.price, c.title AS category
-- FROM products p
-- JOIN categories c ON p.category_id = c.id
-- products хранит category_id, но названия катеории там нет
-- JOIN подтягивает их названия

-- 2)Заказы с именем пользователя
-- SELECT o.id AS order_id, u.name, o.created_at
-- FROM orders2 o 
-- JOIN users2 u ON o.user_id = u.id

-- 3)Состав заказа(позиции)
-- SELECT o.id AS order_id, 
-- u.name,
-- p.title AS product,
-- oi.qty,
-- p.price,
-- (oi.qty * p.price) AS line_sum
-- FROM orders2 o
-- JOIN users2 u ON o.user_id = u.id
-- JOIN order_items oi ON oi.order_id = o.id
-- JOIN products p ON oi.product_id = p.id
-- ORDER BY o.id

-- 4)Иток по каждому заказу
-- SELECT o.id AS order_id,
-- u.name,
-- SUM(oi.qty * p.price) AS order_total
-- FROM orders2 o
-- JOIN users2 u ON o.user_id = u.id
-- JOIN order_items oi ON oi.order_id = o.id
-- JOIN products p ON oi.product_id = p.id
-- GROUP BY o.id, u.name
-- ORDER BY o.id

-- 5)Сколько потратил каждый пользователь
-- SELECT u.name,
-- SUM(oi.qty * p.price) AS spent
-- FROM users2 u
-- JOIN orders2 o ON o.user_id = u.id
-- JOIN order_items oi ON oi.order_id = o.id
-- JOIN products p ON oi.product_id = p.id
-- GROUP BY u.name
-- ORDER BY spent DESC

-- ON ->
-- u.id = o.user_id
-- u.id = o.id

-- 1
-- SELECT
--     p.title AS product_title,
--     p.price,
--     c.title AS category_title
-- FROM products p
-- JOIN categories c ON p.category_id = c.id
-- ORDER BY c.title, p.price DESC;
-- 2
-- SELECT
--     o.id AS order_id,
--     o.created_at
-- FROM orders o
-- JOIN users u ON o.user_id = u.id
-- WHERE u.name = 'Platon'
-- ORDER BY o.created_at ASC;
-- 3
-- SELECT
--     o.id AS order_id,
--     u.name AS user_name,
--     p.title AS product_title,
--     oi.qty,
--     (oi.qty * p.price) AS line_sum
-- FROM orders o
-- JOIN users u ON o.user_id = u.id
-- JOIN order_items oi ON o.id = oi.order_id
-- JOIN products p ON oi.product_id = p.id
-- ORDER BY o.id, p.title;
-- 4
-- SELECT
--     o.id AS order_id,
--     u.name AS user_name,
--     SUM(oi.qty * p.price) AS order_total
-- FROM orders o
-- JOIN users u ON o.user_id = u.id
-- JOIN order_items oi ON o.id = oi.order_id
-- JOIN products p ON oi.product_id = p.id
-- GROUP BY o.id, u.name
-- ORDER BY order_total DESC;
-- 5
-- SELECT
--     p.title AS product_title,
--     c.title AS category_title
-- FROM products p
-- JOIN categories c ON p.category_id = c.id
-- LEFT JOIN order_items oi ON p.id = oi.product_id
-- WHERE oi.product_id IS NULL;
